services:
  db:
    image: mysql:8.4.0
    restart: always
    container_name: fullstack-db
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Pass123!
      MYSQL_DATABASE: fullstack
      MYSQL_USER: codex
      MYSQL_PASSWORD: Pass123!
    volumes:
      - /usr/local/codex/db/mysql_8.4.0:/var/lib/mysql:rw
